Adding integration tests
Pepperi-Addons/create-addon pull request #56
Opened 2023-06-25 11:19 UTC by Chasky-H

2023-06-25 12:14 UTC, saargt requested changes

2023-06-25 12:14 UTC, saargt commented on templates/server-side/typescript/integration-tests/addon.tests.ts
I'd add a comment at the top of the file, saying all new classes extending BaseTest should be exported by the index.ts file, so that these new tests will be returned on the GET tests endpoint

2023-06-26 04:50 UTC, ShirMarciano approved these changes

2023-06-26 05:51 UTC, saargt approved these changes

2023-06-26 06:09 UTC, merged

2023-06-26 10:27 UTC, Chasky-H commented
No need. Template changes don't require a version.
Only changes to the script
________________________________
From: Shir-Pepperi ***@***.***>
Sent: Monday, June 26, 2023 1:25 PM
To: Pepperi-Addons/create-addon ***@***.***>
Cc: Chasky Hoffmann ***@***.***>; Mention ***@***.***>
Subject: Re: [Pepperi-Addons/create-addon] Adding integration tests (PR #56)


@Chasky-H<https://github.com/Chasky-H> you can publish a version

—
Reply to this email directly, view it on GitHub<https://github.com/Pepperi-Addons/create-addon/pull/56#issuecomment-1607169928>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/APN2DHYUB4DV2AYZG4LV4K3XNFPTJANCNFSM6AAAAAAZTC3U54>.
You are receiving this because you were mentioned.Message ID: ***@***.***>